### ISSUE TITLE
Placeholders not generated in .arb files for plural forms

### ISSUE THREAD

**Issue by tobiasbentin** [phrase/flutter_sdk_example#10]
Hello,
when I create a normal phrase key in which I want to insert some value, the generated arb file looks like this:
`"createPollAddUpToImages": "Add up to {value} images",
  "@createPollAddUpToImages": {
    "type": "text",
    "placeholders": {
      "value": {
      }
    }
  },`

and in flutter I can call this key and pass the value like this:
`AppLocalizations.of(context)!.createPollAddUpToImages(2)`

But when I want to do the same for a key that has plural forms the generated arb file does NOT contain the placeholders value.

`"hideReplyOne": "Hide 1 reply",
  "hideReplyOther": "Hide {value} replies",
  "hideReplyZero": "Hide {value} replies",
  "@hideReply": {
    "type": "text"
  },`

Of course I cannot make use of this then:
`AppLocalizations.of(context)!.hideReplyOther(4)`

I could modify the file myself to make it work, but we are importing the arb files from the phrase-translations pull request and let flutter generate the localizations with `flutter pub run phrase`.
And every time I have new keys my old changes would be overwritten.

Is there something I am missing? Or if not, I would really appreciate some fix for that :)

**Comment by jablan** [comment]
@tobiasbentin indeed, that seems to be a bug in generating `arb` files. I will open an internal ticket and report back here when the issue is resolved. Thanks for reporting!

**Comment by tobiasbentin** [comment]
@jablan nice, thank you 😊

**Comment by jablan** [comment]
@tobiasbentin we have deployed a fix for the problem with ARB files. However, the issue is not as simple as it appeared to be. Namely, ARB files do not go well with "traditional" CLDR plurals. As you can see, a translation key with plural forms generates multiple key-values in resulting file. But the opposite is not true, i.e. the import of such file won't know how to handle multiple values and it will treat them as multiple non-plural translation keys.

Therefore, we don't recommend combining ARB files with CLDR plurals. If you can make that choice, please use [ICU plural format](https://support.phrase.com/hc/en-us/articles/5822319545116-ICU-Message-Format-Strings-) with ARB files.

**Comment by tobiasbentin** [comment]
@jablan Thanks for your efforts and the deployed fix but unfortunately this still didn't fix it.
So what I do get generated now is this:
`"viewReplyOne": "View 1 reply",
  "viewReplyOther": "View {number} replies",
  "viewReplyZero": "View 0 replies",
  "@viewReply": {
    "type": "text",
    "placeholders": {
      "number": {
      }
    }
  },`
The viewReply key doesn't exist.

To make it work I would need something like this:
`"viewReplyOne": "View 1 reply",
  "viewReplyOther": "View {number} replies",
  "viewReplyZero": "View 0 replies",
  "@viewReplyOther": {
    "type": "text",
    "placeholders": {
      "number": {
      }
    }
  },`

Is there something else, you or I could do? And if not how are we supposed to switch to icu plural forms?

This is what i've found in the project settings: 
<img width="1137" alt="Screenshot 2023-03-02 at 16 02 25" src="https://user-images.githubusercontent.com/45172447/222466168-476111ac-5604-4df0-b4b4-745a16cda9cb.png">

Or are we supposed to declare the plural forms within the key translations?
For that case I tried this:
`{count, plural, zero {View 0 replies} one{View 1 reply} other{View {count} replies}}`
Generated .arb:
` "viewReply": "{count, plural, zero {View 0 replies} one{View 1 reply} other{View {count} replies}}",
  "@viewReply": {
    "type": "text",
    "placeholders": {
      "count": {
      }
    }
  },`
Which looks fine in my eyes and lets me pass a value to that key.

But if I pass a 1 now in flutter it still uses the translation for other.
Hope you can help me out there :)

**Comment by jablan** [comment]
@tobiasbentin the example ARB file in this project already has an ICU plural: https://github.com/phrase/flutter_sdk_example/blob/main/lib/l10n/app_en.arb#L33 does it work for you out of the box, for different values of `howMany`?

**Comment by docstun** [comment]
Closing this issue for inactivity. Please feel free to reopen if this is still a problem.
